In [8]:
import schedule
import pandas as pd
import time
from datetime import datetime
import random
# datetime object containing current date and time
from bs4 import BeautifulSoup
import requests
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/datasets/Programming_Languages.html"
data =  requests.get(url).text
soup = BeautifulSoup(data, 'html5lib')

In [9]:
def omni_time():
    now = datetime.now()
    # dd/mm/YY H:M:S
    dt_string = now.strftime("%d/%m/%Y %H:%M:%S")
    return dt_string

def webme():
    my_dict = {"Language":[],"Salary":[]};

    for row in soup.find_all('tr'):
        dat = row.find_all('td')
        lang= dat[1].getText()
        pay = dat[3].getText()
        my_dict["Language"].append(lang)
        my_dict["Salary"].append(pay)
    
    df = pd.DataFrame(my_dict)
    yeah = df[1:]
    from sqlalchemy import create_engine
    engine = create_engine('sqlite:///save_pandas.db', echo=True)
    sqlite_connection = engine.connect()
    
    sqlite_table = "forex_predictor"
    yeah.to_sql(sqlite_table, sqlite_connection, if_exists='replace')
    
    sqlite_connection.close()

In [10]:
schedule.every(30).seconds.do(webme)
#to make the schedule run every two seconds
#schedule.every().day.at('12:00').do(webme)
#runs a code at a particular time of day
while True:
    schedule.run_pending()
    time.sleep(1)

2021-06-02 02:41:49,143 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:41:49,144 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,145 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:41:49,146 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,152 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:41:49,154 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,156 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("forex_predictor")
2021-06-02 02:41:49,162 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,170 INFO sqlalchemy.engine.base.Engine
CREATE TABLE forex_predictor (
	"index" BIGINT,
	"Language" TEXT,
	"Salary" TEXT
)


2021-06-02 02:41:49,174 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,295 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:41:49,296 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_forex_predictor_index ON forex_predictor ("index")
2021-06-02 02:41:49,298 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,400 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:41:49,402 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-06-02 02:41:49,403 INFO sqlalchemy.engine.base.Engine INSERT INTO forex_predictor ("index", "Language", "Salary") VALUES (?, ?, ?)
2021-06-02 02:41:49,404 INFO sqlalchemy.engine.base.Engine ((1, 'Python', '$114,383'), (2, 'Java', '$101,013'), (3, 'R', '$92,037'), (4, 'Javascript', '$110,981'), (5, 'Swift', '$130,801'), (6, 'C++', '$113,865'), (7, 'C#', '$88,726'), (8, 'PHP', '$84,727'), (9, 'SQL', '$84,793'), (10, 'Go', '$94,082'))
2021-06-02 02:41:49,408 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:41:49,537 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:41:49,538 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,539 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:41:49,540 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,543 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Forex Predictor")
2021-06-02 02:41:49,544 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,547 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Forex Predictor")
2021-06-02 02:41:49,550 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,552 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-06-02 02:41:49,553 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,556 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Forex Predictor")
2021-06-02 02:41:49,557 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,559 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'Forex Predictor' AND type = 'table'
2021-06-02 02:41:49,563 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,567 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("Forex Predictor")
2021-06-02 02:41:49,568 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,572 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("Forex Predictor")
2021-06-02 02:41:49,574 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,576 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'Forex Predictor' AND type = 'table'
2021-06-02 02:41:49,578 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,579 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("Forex Predictor")
2021-06-02 02:41:49,581 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,582 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_Forex Predictor_index")
2021-06-02 02:41:49,583 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,585 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("Forex Predictor")
2021-06-02 02:41:49,587 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,589 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_Forex Predictor_index")
2021-06-02 02:41:49,590 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,592 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'Forex Predictor' AND type = 'table'
2021-06-02 02:41:49,593 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,595 INFO sqlalchemy.engine.base.Engine
DROP TABLE "Forex Predictor"
2021-06-02 02:41:49,597 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,698 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:41:49,701 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Forex Predictor" (
	"index" BIGINT,
	"Language" TEXT,
	"Salary" TEXT
)


2021-06-02 02:41:49,703 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,789 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:41:49,791 INFO sqlalchemy.engine.base.Engine CREATE INDEX "ix_Forex Predictor_index" ON "Forex Predictor" ("index")
2021-06-02 02:41:49,792 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:41:49,955 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:41:49,959 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-06-02 02:41:49,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "Forex Predictor" ("index", "Language", "Salary") VALUES (?, ?, ?)
2021-06-02 02:41:49,969 INFO sqlalchemy.engine.base.Engine ((1, 'Python', '$114,383'), (2, 'Java', '$101,013'), (3, 'R', '$92,037'), (4, 'Javascript', '$110,981'), (5, 'Swift', '$130,801'), (6, 'C++', '$113,865'), (7, 'C#', '$88,726'), (8, 'PHP', '$84,727'), (9, 'SQL', '$84,793'), (10, 'Go', '$94,082'))
2021-06-02 02:41:49,977 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:41:50,119 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-06-02 02:41:50,121 INFO sqlalchemy.engine.base.Engine ()
      Language    Salary
1       Python  $114,383
2         Java  $101,013
3            R   $92,037
4   Javascript  $110,981
5        Swift  $130,801
6          C++  $113,865
7           C#   $88,726
8          PHP   $84,727
9          SQL   $84,793
10          Go   $94,082
2021-06-02 02:42:19,165 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:19,166 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,167 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:19,169 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,173 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:19,176 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,178 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:19,179 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,181 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-06-02 02:42:19,183 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,186 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:19,201 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,206 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:19,213 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,215 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("forex_predictor")
2021-06-02 02:42:19,217 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,220 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("forex_predictor")
2021-06-02 02:42:19,226 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,229 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'

2021-06-02 02:42:19,231 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,233 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("forex_predictor")
2021-06-02 02:42:19,236 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,250 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_forex_predictor_index")
2021-06-02 02:42:19,253 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,258 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("forex_predictor")
2021-06-02 02:42:19,260 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,274 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_forex_predictor_index")
2021-06-02 02:42:19,277 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,281 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:19,283 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,285 INFO sqlalchemy.engine.base.Engine
DROP TABLE forex_predictor
2021-06-02 02:42:19,288 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,437 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:19,440 INFO sqlalchemy.engine.base.Engine
CREATE TABLE forex_predictor (
	"index" BIGINT,
	"Language" TEXT,
	"Salary" TEXT
)


2021-06-02 02:42:19,441 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,569 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:19,572 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_forex_predictor_index ON forex_predictor ("index")
2021-06-02 02:42:19,573 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:19,695 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:19,700 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-06-02 02:42:19,702 INFO sqlalchemy.engine.base.Engine INSERT INTO forex_predictor ("index", "Language", "Salary") VALUES (?, ?, ?)
2021-06-02 02:42:19,704 INFO sqlalchemy.engine.base.Engine ((1, 'Python', '$114,383'), (2, 'Java', '$101,013'), (3, 'R', '$92,037'), (4, 'Javascript', '$110,981'), (5, 'Swift', '$130,801'), (6, 'C++', '$113,865'), (7, 'C#', '$88,726'), (8, 'PHP', '$84,727'), (9, 'SQL', '$84,793'), (10, 'Go', '$94,082'))
2021-06-02 02:42:19,709 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:20,846 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:20,846 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,848 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:20,849 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,855 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:20,856 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,858 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:20,861 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,863 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-06-02 02:42:20,867 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,871 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:20,873 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,878 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:20,881 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,883 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("forex_predictor")
2021-06-02 02:42:20,890 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,893 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("forex_predictor")
2021-06-02 02:42:20,897 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,899 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:20,900 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,904 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("forex_predictor")
2021-06-02 02:42:20,906 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,908 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_forex_predictor_index")
2021-06-02 02:42:20,909 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,913 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("forex_predictor")
2021-06-02 02:42:20,920 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,924 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_forex_predictor_index")
2021-06-02 02:42:20,926 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,929 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:20,931 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:20,934 INFO sqlalchemy.engine.base.Engine
DROP TABLE forex_predictor
2021-06-02 02:42:20,936 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,095 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:21,102 INFO sqlalchemy.engine.base.Engine
CREATE TABLE forex_predictor (
	"index" BIGINT,
	"Language" TEXT,
	"Salary" TEXT
)


2021-06-02 02:42:21,107 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,310 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:21,311 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_forex_predictor_index ON forex_predictor ("index")
2021-06-02 02:42:21,312 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,533 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:21,536 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-06-02 02:42:21,539 INFO sqlalchemy.engine.base.Engine INSERT INTO forex_predictor ("index", "Language", "Salary") VALUES (?, ?, ?)
2021-06-02 02:42:21,541 INFO sqlalchemy.engine.base.Engine ((1, 'Python', '$114,383'), (2, 'Java', '$101,013'), (3, 'R', '$92,037'), (4, 'Javascript', '$110,981'), (5, 'Swift', '$130,801'), (6, 'C++', '$113,865'), (7, 'C#', '$88,726'), (8, 'PHP', '$84,727'), (9, 'SQL', '$84,793'), (10, 'Go', '$94,082'))
2021-06-02 02:42:21,558 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:21,727 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:21,728 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,730 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:21,733 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,737 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Forex Predictor")
2021-06-02 02:42:21,737 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,739 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Forex Predictor")
2021-06-02 02:42:21,741 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,746 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-06-02 02:42:21,749 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,752 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Forex Predictor")
2021-06-02 02:42:21,754 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,758 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'Forex Predictor' AND type = 'table'
2021-06-02 02:42:21,760 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,762 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("Forex Predictor")
2021-06-02 02:42:21,764 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,767 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("Forex Predictor")
2021-06-02 02:42:21,769 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,772 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'Forex Predictor' AND type = 'table'

2021-06-02 02:42:21,782 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,788 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("Forex Predictor")
2021-06-02 02:42:21,790 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,792 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_Forex Predictor_index")
2021-06-02 02:42:21,794 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,797 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("Forex Predictor")
2021-06-02 02:42:21,799 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,801 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_Forex Predictor_index")
2021-06-02 02:42:21,802 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,805 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'Forex Predictor' AND type = 'table'
2021-06-02 02:42:21,808 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,813 INFO sqlalchemy.engine.base.Engine
DROP TABLE "Forex Predictor"
2021-06-02 02:42:21,815 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,906 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:21,911 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Forex Predictor" (
	"index" BIGINT,
	"Language" TEXT,
	"Salary" TEXT
)


2021-06-02 02:42:21,912 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:21,996 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:21,998 INFO sqlalchemy.engine.base.Engine CREATE INDEX "ix_Forex Predictor_index" ON "Forex Predictor" ("index")
2021-06-02 02:42:21,999 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:22,094 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:22,099 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-06-02 02:42:22,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "Forex Predictor" ("index", "Language", "Salary") VALUES (?, ?, ?)
2021-06-02 02:42:22,104 INFO sqlalchemy.engine.base.Engine ((1, 'Python', '$114,383'), (2, 'Java', '$101,013'), (3, 'R', '$92,037'), (4, 'Javascript', '$110,981'), (5, 'Swift', '$130,801'), (6, 'C++', '$113,865'), (7, 'C#', '$88,726'), (8, 'PHP', '$84,727'), (9, 'SQL', '$84,793'), (10, 'Go', '$94,082'))
2021-06-02 02:42:22,112 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:22,227 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-06-02 02:42:22,228 INFO sqlalchemy.engine.base.Engine ()
      Language    Salary
1       Python  $114,383
2         Java  $101,013
3            R   $92,037
4   Javascript  $110,981
5        Swift  $130,801
6          C++  $113,865
7           C#   $88,726
8          PHP   $84,727
9          SQL   $84,793
10          Go   $94,082
2021-06-02 02:42:50,260 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:50,261 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,262 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:50,263 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,266 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:50,267 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,270 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:50,272 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,273 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-06-02 02:42:50,276 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,285 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:50,288 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,291 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:50,292 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,294 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("forex_predictor")
2021-06-02 02:42:50,296 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,298 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("forex_predictor")
2021-06-02 02:42:50,301 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,303 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:50,305 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,306 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("forex_predictor")
2021-06-02 02:42:50,307 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,308 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_forex_predictor_index")
2021-06-02 02:42:50,309 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,311 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("forex_predictor")
2021-06-02 02:42:50,312 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,314 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_forex_predictor_index")
2021-06-02 02:42:50,315 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,316 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:50,317 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,319 INFO sqlalchemy.engine.base.Engine
DROP TABLE forex_predictor
2021-06-02 02:42:50,320 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,490 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:50,492 INFO sqlalchemy.engine.base.Engine
CREATE TABLE forex_predictor (
	"index" BIGINT,
	"Language" TEXT,
	"Salary" TEXT
)


2021-06-02 02:42:50,493 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,588 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:50,590 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_forex_predictor_index ON forex_predictor ("index")
2021-06-02 02:42:50,593 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:50,729 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:50,733 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-06-02 02:42:50,735 INFO sqlalchemy.engine.base.Engine INSERT INTO forex_predictor ("index", "Language", "Salary") VALUES (?, ?, ?)
2021-06-02 02:42:50,735 INFO sqlalchemy.engine.base.Engine ((1, 'Python', '$114,383'), (2, 'Java', '$101,013'), (3, 'R', '$92,037'), (4, 'Javascript', '$110,981'), (5, 'Swift', '$130,801'), (6, 'C++', '$113,865'), (7, 'C#', '$88,726'), (8, 'PHP', '$84,727'), (9, 'SQL', '$84,793'), (10, 'Go', '$94,082'))
2021-06-02 02:42:50,749 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:51,990 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:51,991 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:51,995 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:51,997 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,000 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:52,002 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,003 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:52,005 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,008 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-06-02 02:42:52,010 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,012 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("forex_predictor")
2021-06-02 02:42:52,013 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,016 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:52,018 INFO sqlalchemy.engine.base.Engine ()

2021-06-02 02:42:52,021 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("forex_predictor")
2021-06-02 02:42:52,023 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,025 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("forex_predictor")
2021-06-02 02:42:52,027 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,031 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:52,032 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,035 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("forex_predictor")
2021-06-02 02:42:52,036 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,038 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_forex_predictor_index")
2021-06-02 02:42:52,039 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,041 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("forex_predictor")
2021-06-02 02:42:52,041 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,043 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_forex_predictor_index")
2021-06-02 02:42:52,044 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,046 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'forex_predictor' AND type = 'table'
2021-06-02 02:42:52,048 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,051 INFO sqlalchemy.engine.base.Engine
DROP TABLE forex_predictor
2021-06-02 02:42:52,053 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,278 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:52,281 INFO sqlalchemy.engine.base.Engine
CREATE TABLE forex_predictor (
	"index" BIGINT,
	"Language" TEXT,
	"Salary" TEXT
)


2021-06-02 02:42:52,284 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,404 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:52,405 INFO sqlalchemy.engine.base.Engine CREATE INDEX ix_forex_predictor_index ON forex_predictor ("index")
2021-06-02 02:42:52,406 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:52,635 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:52,638 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-06-02 02:42:52,640 INFO sqlalchemy.engine.base.Engine INSERT INTO forex_predictor ("index", "Language", "Salary") VALUES (?, ?, ?)
2021-06-02 02:42:52,642 INFO sqlalchemy.engine.base.Engine ((1, 'Python', '$114,383'), (2, 'Java', '$101,013'), (3, 'R', '$92,037'), (4, 'Javascript', '$110,981'), (5, 'Swift', '$130,801'), (6, 'C++', '$113,865'), (7, 'C#', '$88,726'), (8, 'PHP', '$84,727'), (9, 'SQL', '$84,793'), (10, 'Go', '$94,082'))
2021-06-02 02:42:52,647 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:53,767 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:53,768 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,769 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-06-02 02:42:53,769 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,772 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Forex Predictor")
2021-06-02 02:42:53,774 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,777 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Forex Predictor")
2021-06-02 02:42:53,779 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,784 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-06-02 02:42:53,785 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,789 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("Forex Predictor")
2021-06-02 02:42:53,791 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,794 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'Forex Predictor' AND type = 'table'
2021-06-02 02:42:53,795 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,799 INFO sqlalchemy.engine.base.Engine PRAGMA main.foreign_key_list("Forex Predictor")
2021-06-02 02:42:53,801 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,804 INFO sqlalchemy.engine.base.Engine PRAGMA temp.foreign_key_list("Forex Predictor")
2021-06-02 02:42:53,806 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,808 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'Forex Predictor' AND type = 'table'
2021-06-02 02:42:53,811 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,813 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("Forex Predictor")
2021-06-02 02:42:53,814 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,825 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_Forex Predictor_index")
2021-06-02 02:42:53,848 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,850 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_list("Forex Predictor")
2021-06-02 02:42:53,853 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,856 INFO sqlalchemy.engine.base.Engine PRAGMA main.index_info("ix_Forex Predictor_index")
2021-06-02 02:42:53,858 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,861 INFO sqlalchemy.engine.base.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = 'Forex Predictor' AND type = 'table'
2021-06-02 02:42:53,863 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:53,865 INFO sqlalchemy.engine.base.Engine
DROP TABLE "Forex Predictor"
2021-06-02 02:42:53,866 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:54,071 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:54,074 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "Forex Predictor" (
	"index" BIGINT,
	"Language" TEXT,
	"Salary" TEXT
)


2021-06-02 02:42:54,075 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:54,169 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:54,171 INFO sqlalchemy.engine.base.Engine CREATE INDEX "ix_Forex Predictor_index" ON "Forex Predictor" ("index")
2021-06-02 02:42:54,174 INFO sqlalchemy.engine.base.Engine ()
2021-06-02 02:42:54,276 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:54,280 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-06-02 02:42:54,281 INFO sqlalchemy.engine.base.Engine INSERT INTO "Forex Predictor" ("index", "Language", "Salary") VALUES (?, ?, ?)
2021-06-02 02:42:54,283 INFO sqlalchemy.engine.base.Engine ((1, 'Python', '$114,383'), (2, 'Java', '$101,013'), (3, 'R', '$92,037'), (4, 'Javascript', '$110,981'), (5, 'Swift', '$130,801'), (6, 'C++', '$113,865'), (7, 'C#', '$88,726'), (8, 'PHP', '$84,727'), (9, 'SQL', '$84,793'), (10, 'Go', '$94,082'))
2021-06-02 02:42:54,313 INFO sqlalchemy.engine.base.Engine COMMIT
2021-06-02 02:42:54,499 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-06-02 02:42:54,501 INFO sqlalchemy.engine.base.Engine ()
      Language    Salary
1       Python  $114,383
2         Java  $101,013
3            R   $92,037
4   Javascript  $110,981
5        Swift  $130,801
6          C++  $113,865
7           C#   $88,726
8          PHP   $84,727
9          SQL   $84,793
10          Go   $94,082

KeyboardInterrupt: